/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\billboard.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mia.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Cube001_Material001_0.geometry} material={materials['Material.001']} position={[0, 999.827, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/billboard.glb')
